# Generated by Django 4.2.7 on 2024-05-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='body',
            new_name='user',
        ),
    ]
